FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY docker/30-runtime-config.sh /docker-entrypoint.d/
RUN chmod +x /docker-entrypoint.d/30-runtime-config.sh
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
